> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Five interesting Numpy array functions


### These are my 5 functions intrested me when going through the documentation.

Write a short introduction about Numpy and list the chosen functions. 

- numpy.unique: This function returns the unique elements of an array. It can also return the indices of the original array that correspond to the unique elements, or the counts of how many times each unique element appears in the array.

- numpy.flip: This function reverses the order of elements in an array along a specified axis. It can also be used to reverse the order of the dimensions of a multi-dimensional array.

- numpy.pad: This function pads an array with zeros or other specified values along one or more axes. This can be useful when preparing data for convolutional neural networks or other operations that require a fixed input size.

- numpy.tile: This function creates a new array by repeating an existing array a specified number of times along each axis. This can be useful when preparing data for machine learning models that require fixed-sized inputs.

- numpy.clip: The numpy.clip function is used to clip (or limit) the values in a given array between a specified minimum and maximum value. It returns a new array with the clipped values.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.unique
function2 = np.flip
function3 = np.pad
function4 = np.tile
function5 = np.clip

## Function 1 - np.unique

This function returns the unique elements of an array. It can also return the indices of the original array that correspond to the unique elements, or the counts of how many times each unique element appears in the array.

In [3]:
# Example 1 - working

arr = np.array([1, 2, 3, 3, 4, 4, 4, 5])
unique_vals = np.unique(arr)
print(unique_vals)

[1 2 3 4 5]


In this example, the np.unique function is used to find the unique elements of an array arr. The output shows that there are five unique elements in the array: 1, 2, 3, 4, and 5.

In [5]:
# Example 2 - working
arr = np.array([[1, 2], [2, 3], [3, 4], [3, 4]])
unique_vals, indices = np.unique(arr, return_index=True)
print(unique_vals)
print(indices)

[1 2 3 4]
[0 1 3 5]


In this example, the np.unique function is used to find the unique elements of a 2D array arr. The return_index argument is set to True, which means that the function also returns the indices of the original array that correspond to the unique elements. The output shows that there are four unique elements in the array: [1, 2], [2, 3], [3, 4], and [4, 5]. The indices array shows that the first occurrence of each unique element is at index 0, 1, 2, and 3 respectively.

In [6]:
# Example 3 - breaking

arr = np.array([1, 2, 3, 3, 4, 4, 4, 5])
unique_vals = np.unique(arr, foo='bar')

TypeError: _unique_dispatcher() got an unexpected keyword argument 'foo'

In this example, the np.unique function is called with an invalid argument foo. This will result in a TypeError with the message: "unique() got an unexpected keyword argument 'foo'". The correct keyword argument is return_counts which will return the counts of each unique value in the array.

This function is useful when you want to find the unique elements of an array, which can be used to identify unique values or remove duplicate values from an array.

## Function 2 - np.flip

This function reverses the order of elements in an array along a specified axis. It can also be used to reverse the order of the dimensions of a multi-dimensional array.

In [7]:
# Example 1 - working

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_arr = np.flip(arr, axis=0)
print(flipped_arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In this example, the numpy.flip function is used to reverse the order of the rows in a 2D array arr. The axis argument is set to 0, which means that the function reverses the rows. The output shows that the order of the rows in the array has been reversed.

In [8]:
# Example 2 - working

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_arr = np.flip(arr, axis=1)
print(flipped_arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In this example, the numpy.flip function is used to reverse the order of the columns in a 2D array arr. The axis argument is set to 1, which means that the function reverses the columns. The output shows that the order of the columns in the array has been reversed.

In [9]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array([1, 2, 3, 4, 5])
flipped_arr = np.flip(arr, axes=1)

TypeError: _flip_dispatcher() got an unexpected keyword argument 'axes'

In this example, the numpy.flip function is called with an invalid argument axes. This will result in a TypeError with the message: "flip() got an unexpected keyword argument 'axes'". The correct keyword argument is axis which takes an integer or tuple of integers representing the axis or axes to be flipped.

This function is useful when you want to reverse the order of elements in an array, which can be useful for data processing or when working with time series data.

## Function 3 - np.pad

This function pads an array with zeros or other specified values along one or more axes. This can be useful when preparing data for convolutional neural networks or other operations that require a fixed input size.

In [10]:
# Example 1 - working

arr = np.array([[1, 2], [3, 4]])
padded_arr = np.pad(arr, ((1, 1), (1, 1)), mode='constant')
print(padded_arr)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In this example, the numpy.pad function is used to pad an array arr with zeros along both dimensions. The second argument ((1, 1), (1, 1)) specifies how many zeros to pad along each dimension. The mode argument is set to 'constant', which means that the padding values will be constant (in this case, zero). The output shows the original array surrounded by a border of zeros.

In [11]:
# Example 2 - working

arr = np.array([1, 2, 3])
padded_arr = np.pad(arr, (2, 3), mode='edge')
print(padded_arr)

[1 1 1 2 3 3 3 3]


In this example, the numpy.pad function is used to pad a 1D array arr with the edge values of the array. The second argument (2, 3) specifies how many elements to pad before and after the array. The mode argument is set to 'edge', which means that the padding values will be the edge values of the array. The output shows the original array with the edge values repeated at the beginning and end of the array.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array([[1, 2], [3, 4]])
padded_arr = np.pad(arr, ((1, 1), (1, 2)), mode='foo')

ValueError: mode 'foo' is not supported

In this example, the numpy.pad function is called with an invalid value for the mode argument. This will result in a ValueError with the message: "Padding mode 'foo' not supported". The mode argument can only take certain values (such as 'constant', 'edge', or 'wrap') and passing an invalid value will raise an error.

This function is useful when you want to add padding to an array, which can be helpful when preparing data for convolutional neural networks or other operations that require a fixed input size.

## Function 4 - np.tile

This function creates a new array by repeating an existing array a specified number of times along each axis. This can be useful when preparing data for machine learning models that require fixed-sized inputs.

In [13]:
# Example 1 - working

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
matmul_arr = np.matmul(arr1, arr2)
print(matmul_arr)

[[19 22]
 [43 50]]


In this example, the numpy.matmul function is used to perform matrix multiplication on two 2D arrays arr1 and arr2. The output shows the result of the matrix multiplication.

In [14]:
# Example 2 - working

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10], [11, 12]])
matmul_arr = np.matmul(arr1, arr2)
print(matmul_arr)

[[ 58  64]
 [139 154]]


In this example, the numpy.matmul function is used to perform matrix multiplication on two 2D arrays arr1 and arr2, where arr1 has 2 rows and 3 columns and arr2 has 3 rows and 2 columns. The output shows the result of the matrix multiplication.

In [17]:
# Example 3 - breaking (to illustrate when it breaks)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([5, 6],[1])
matmul_arr = np.matmul(arr1, arr2)
print(matmul_arr)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In this example, the numpy.matmul function is called with invalid dimensions for the input arrays. This will result in a ValueError with the message: "matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?)". The error message indicates that the dimensions of the input arrays are not compatible for matrix multiplication. Specifically, arr1 has dimensions (2, 2) and arr2 has dimensions (2,), which is not a valid combination for matrix multiplication.

This function is useful when you want to repeat an array multiple times along one or more axes, which can be useful when preparing data for machine learning models that require fixed-sized inputs.

## Function 5 - np.clip

The numpy.clip function is used to clip (or limit) the values in a given array between a specified minimum and maximum value. It returns a new array with the clipped values.

In [18]:
# Example 1 - working

arr = np.array([1, 2, 3, 4, 5])
clipped_arr = np.clip(arr, 2, 4)
print(clipped_arr)

[2 2 3 4 4]


In this example, the numpy.clip function is used to clip the values in an array arr between the minimum value of 2 and the maximum value of 4. The output shows the clipped array.

In [19]:
# Example 2 - working

arr = np.array([[1, 2, 3], [4, 5, 6]])
clipped_arr = np.clip(arr, 2, 4)
print(clipped_arr)

[[2 2 3]
 [4 4 4]]


In this example, the numpy.clip function is used to clip the values in a 2D array arr between the minimum value of 2 and the maximum value of 4. The output shows the clipped array.

In [27]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array([1, 2, 3, 4, 5])
clipped_arr = np.clip(arr, 'a', 'b')
print(clipped_arr)

UFuncTypeError: ufunc 'clip' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In this example, the numpy.clip function is called with non-numeric arguments for the clipping values. This will result in a TypeError with the message: "Cannot cast ufunc 'minimum' output from dtype('<U1') to dtype('int64') with casting rule 'same_kind'". The error message indicates that the clipping values passed as arguments should be numeric, but here, they are string values ('a' and 'b'). This will raise a TypeError as the clip function can only operate on numeric arrays.

This function is useful when you want to limit the range of values in an array to a specified range, which can be helpful when processing image data or other types of data that have a known range of values.

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sridharstreaks/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/sridharstreaks/numpy-array-operations


'https://jovian.com/sridharstreaks/numpy-array-operations'